import type { ColorInstrument, ColorConfig, ScaleConfig } from './colors.js'
import {
  generatePenColors,
  generatePencilColors,
  generatePaperColors,
  defaultPaperOptions,
  defaultTextContrast,
  resolveTextContrast,
  type PaperOptions,
  type TextContrast,
} from './generate-colors.js'

const arrayOf12 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

/** Page backgrounds the pen/pencil scales are anchored to and composited against, per mode. */
export type ColorBackgrounds = {
  light?: string
  dark?: string
}

export interface ColorCssOptions {
  /** Page backgrounds the pen/pencil scales are anchored to and composited against, per mode. */
  backgrounds?: ColorBackgrounds
  /** Paper generation knobs; recorded in the generated CSS header. */
  paper?: PaperOptions
  /** WCAG contrast the text step (11) is solved to against the page, single or per-mode; recorded in the header. */
  textContrast?: TextContrast
}

export function generateColorCss(name: string, baseColor: string, options?: ColorCssOptions) {
  const color = baseColor.toLowerCase()
  const backgrounds = options?.backgrounds
  const paperOptions = { ...defaultPaperOptions, ...options?.paper }
  const textContrast = options?.textContrast ?? defaultTextContrast

  const lightPen = generatePenColors('light', color, backgrounds?.light, textContrast)
  const lightPencil = generatePencilColors('light', color, backgrounds?.light, textContrast)
  const lightPaper = generatePaperColors('light', color, paperOptions)
  const darkPen = generatePenColors('dark', color, backgrounds?.dark, textContrast)
  const darkPencil = generatePencilColors('dark', color, backgrounds?.dark, textContrast)
  const darkPaper = generatePaperColors('dark', color, paperOptions)

  return getColorCss(
    name,
    color,
    lightPen,
    lightPencil,
    lightPaper,
    darkPen,
    darkPencil,
    darkPaper,
    paperOptions,
    textContrast,
  )
}

export function getColorCss(
  name: string,
  baseColor: string,
  lightPen: ColorConfig,
  lightPencil: ColorConfig,
  lightPaper: ColorConfig,
  darkPen: ColorConfig,
  darkPencil: ColorConfig,
  darkPaper: ColorConfig,
  paperOptions: Required<PaperOptions> = defaultPaperOptions,
  textContrast: TextContrast = defaultTextContrast,
): string {
  const title = name.charAt(0).toUpperCase() + name.slice(1)

  return `\
/**
 * Auto Generated by Utensil Color Generation.
 * ${title}
 * color: ${baseColor}
 * light-background ${lightPen.background}
 * dark-background ${darkPen.background}
 * paper-anchor ${paperOptions.anchor}
 * paper-tint ${paperOptions.tint}
 * paper-step-contrast ${paperOptions.stepContrast}
 * light-text-contrast ${resolveTextContrast('light', textContrast)}
 * dark-text-contrast ${resolveTextContrast('dark', textContrast)}
**/
@layer utensil, app, utensil-utilities;

@layer utensil {
  :root,
  .light-mode {
    ${colorScale(name, 'pen', 4, lightPen.standard, lightPen.contrast, lightPen.source)}

    ${colorScale(name, 'pencil', 4, lightPencil.standard, lightPencil.contrast, lightPencil.source)}

    ${colorScale(name, 'paper', 4, lightPaper.standard, lightPaper.contrast, lightPaper.source)}
  }

  .dark-mode {
    ${colorScale(name, 'pen', 4, darkPen.standard, darkPen.contrast, darkPen.source)}

    ${colorScale(name, 'pencil', 4, darkPencil.standard, darkPencil.contrast, darkPencil.source)}

    ${colorScale(name, 'paper', 4, darkPaper.standard, darkPaper.contrast, darkPaper.source)}
  }

  @supports (color: color(display-p3 1 1 1)) {
    @media (color-gamut: p3) {
      :root,
      .light-mode {
        ${colorScale(name, 'pen', 8, lightPen.wideGamut)}

        ${colorScale(name, 'pencil', 8, lightPencil.wideGamut)}

        ${colorScale(name, 'paper', 8, lightPaper.wideGamut)}
      }

      .dark-mode {
        ${colorScale(name, 'pen', 8, darkPen.wideGamut)}

        ${colorScale(name, 'pencil', 8, darkPencil.wideGamut)}

        ${colorScale(name, 'paper', 8, darkPaper.wideGamut)}
      }
    }
  }

${getColorAssignmentCss(name, 'pen')}

${getColorAssignmentCss(name, 'pencil')}

${getColorAssignmentCss(name, 'paper')}
}
`
}

function getColorAssignmentCss(name: string, instrument: string): string {
  const steps = instrument === 'paper' ? [0, ...arrayOf12] : arrayOf12
  return `\
  .${name}-${instrument} {
    ${steps.map((index) => `--${instrument}-${index}: var(--${name}-${instrument}-${index});`).join('\n    ')}
    ${arrayOf12.map((index) => `--${instrument}-a${index}: var(--${name}-${instrument}-a${index});`).join('\n    ')}
    --${instrument}-contrast: var(--${name}-${instrument}-contrast);
    --${instrument}-surface: var(--${name}-${instrument}-surface);
    --${instrument}-indicator: var(--${name}-${instrument}-indicator);
    --${instrument}-track: var(--${name}-${instrument}-track);
    --${instrument}-brand: var(--${name}-${instrument}-brand);
  }`
}

function colorScale(
  name: string,
  instrument: ColorInstrument,
  indent: number,
  config: ScaleConfig,
  contrast?: string,
  brand?: string,
): string {
  const css = `
    ${config.inset ? `--${name}-${instrument}-0: ${config.inset};` : ''}
    ${config.scale.map((value, index) => `--${name}-${instrument}-${index + 1}: ${value};`).join('\n  ')}

    ${config.alphaScale.map((value, index) => `--${name}-${instrument}-a${index + 1}: ${value};`).join('\n  ')}

    ${contrast ? `--${name}-${instrument}-contrast: ${contrast};` : ''}
    --${name}-${instrument}-surface: ${config.surface};
    --${name}-${instrument}-indicator: ${config.scale[8]};
    --${name}-${instrument}-track: ${config.scale[8]};
    ${brand ? `--${name}-${instrument}-brand: ${brand};` : ''}
  `

  return css
    .trim()
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => !!line)
    .join('\n' + ' '.repeat(indent))
}
