// Verifies utensil-css and utensil-vue as a consumer installs them: packs both packages, installs
// the tarballs into a copy of fixtures/consumer, then typechecks, builds and inspects the result.
//
//   bun scripts/verify-package.ts [--no-build] [--keep]

import { $ } from 'bun'
import { cpSync, existsSync, mkdtempSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')
const args = process.argv.slice(2)
const failures: string[] = []

function check(ok: boolean, message: string) {
  console.log(`${ok ? '✓' : '✗'} ${message}`)
  if (!ok) failures.push(message)
}

if (!args.includes('--no-build')) {
  await $`bun run build`.cwd(root)
}

for (const pkg of ['css', 'vue']) {
  const lint = await $`bunx publint`
    .cwd(join(root, 'packages', pkg))
    .nothrow()
    .quiet()
  check(lint.exitCode === 0 && lint.stdout.toString().includes('All good'), `publint utensil-${pkg}`)
}

const work = mkdtempSync(join(tmpdir(), 'utensil-verify-'))
console.log(`Working in ${work}`)

for (const pkg of ['css', 'vue']) {
  await $`bun pm pack --destination ${work} --quiet`.cwd(join(root, 'packages', pkg))
  const tarball = readdirSync(work).find((f) => f.startsWith(`utensil-${pkg}-`) && f.endsWith('.tgz'))!
  renameSync(join(work, tarball), join(work, `utensil-${pkg}.tgz`))
}

// Types resolve for bundler consumers (Vite); utensil-css also supports Node16 ESM.
const attwCss =
  await $`bunx attw ${join(work, 'utensil-css.tgz')} --profile esm-only --entrypoints colors/generate-css colors/generate-colors colors/colors`
    .nothrow()
    .quiet()
check(attwCss.exitCode === 0, 'attw utensil-css (node16 + bundler)')
const vueEntrypoints = [
  'components/button/UtensilButton.vue',
  'theme/UtensilThemeRoot.vue',
  'theme/utensil-theme',
  'theme/useUserThemePreferences',
  'composables/use-keys',
  'utensil-css-inline',
]
const attwVue = await $`bunx attw ${join(work, 'utensil-vue.tgz')} --format json --entrypoints ${vueEntrypoints}`
  .nothrow()
  .quiet()
const attwResult = JSON.parse(attwVue.stdout.toString())
const bundlerProblems = (attwResult.analysis?.problems ?? []).filter(
  (p: { resolutionKind?: string }) => p.resolutionKind === 'bundler',
)
check(bundlerProblems.length === 0, 'attw utensil-vue (bundler)')

const app = join(work, 'consumer')
cpSync(join(root, 'fixtures', 'consumer'), app, {
  recursive: true,
  filter: (src) => !src.includes('node_modules') && !src.includes(`${join('consumer', 'dist')}`),
})
await $`bun install --no-save`.cwd(app).quiet()

const installed = JSON.parse(readFileSync(join(app, 'node_modules/utensil-vue/package.json'), 'utf8'))
check(installed.dependencies['utensil-css'] === installed.version, 'utensil-vue pins utensil-css to its own version')
check(
  !existsSync(join(app, 'node_modules/utensil-vue/src/components/button/UtensilButton.test.ts')),
  'tests are not shipped',
)
check(
  existsSync(join(app, 'node_modules/utensil-vue/src/components/button/UtensilButtonDoc.vue')),
  'source and API docs are shipped',
)
check(existsSync(join(app, 'node_modules/utensil-vue/docs/USAGE.md')), 'docs are shipped')
check(existsSync(join(app, 'node_modules/utensil-vue/LICENSE.md')), 'license is shipped')

const typecheck = await $`bun run typecheck`.cwd(app).nothrow()
check(typecheck.exitCode === 0, 'consumer typechecks with typed wrappers (and rejects an invalid color)')

const test = await $`bun run test`.cwd(app).nothrow()
check(test.exitCode === 0, 'consumer tests run with Vitest (utensil-vue inlined)')

const build = await $`bun run build`.cwd(app).nothrow()
check(build.exitCode === 0, 'consumer builds')

if (build.exitCode === 0) {
  const assets = join(app, 'dist', 'assets')
  const read = (ext: string) =>
    readdirSync(assets)
      .filter((f) => f.endsWith(ext))
      .map((f) => readFileSync(join(assets, f), 'utf8'))
      .join('\n')
  const js = read('.js')
  const css = read('.css')

  check(css.includes('.utensil-button'), 'used component CSS is bundled')
  check(css.indexOf('@layer utensil, app, utensil-utilities') === css.indexOf('@layer'), 'layer order comes first')
  const unused = [
    'utensil-date-picker',
    'utensil-calendar',
    'utensil-select',
    'utensil-table',
    'utensil-deck',
    'utensil-data-viz',
    'utensil-color-picker',
    'utensil-slideshow',
  ]
  const leakedJs = unused.filter((name) => js.includes(name))
  const leakedCss = unused.filter((name) => css.includes(`.${name}`))
  check(leakedJs.length === 0, `unused components tree-shaken from JS ${leakedJs.join(', ')}`)
  check(leakedCss.length === 0, `unused components tree-shaken from CSS ${leakedCss.join(', ')}`)
}

// CSS-only usage: the bundled stylesheet plus a color generated by the CLI.
const generated = await $`node node_modules/.bin/utensil-generate-color blue '#0093ee'`.cwd(app).nothrow().quiet()
check(
  generated.exitCode === 0 && generated.stdout.toString().includes('.blue-pen'),
  'utensil-generate-color CLI runs on Node',
)
writeFileSync(join(app, 'plain', 'blue.css'), generated.stdout.toString())
const bundle = readFileSync(join(app, 'node_modules/utensil-css/dist/utensil.css'), 'utf8')
check(bundle.trimStart().startsWith('/* utensil-layers.css */'), 'utensil.css leads with the layer order')
check(bundle.includes('.utensil-calculate'), 'utensil.css includes the theme calculations')

const skillsDir = join(app, 'node_modules/utensil-vue/skills')
const skills = existsSync(skillsDir) ? readdirSync(skillsDir) : []
check(skills.length > 0, `skills are shipped (${skills.join(', ')})`)
for (const skill of skills) {
  const md = readFileSync(join(skillsDir, skill, 'SKILL.md'), 'utf8')
  check(new RegExp(`^---\\nname: ${skill}\\n`).test(md), `skill ${skill} has matching frontmatter name`)
}

// Consumers link the shipped skills into their agents' skill folders with skills-npm.
const linked = await $`bunx skills-npm@4 --agents claude-code --yes`.cwd(app).nothrow().quiet()
const linkedSkills = existsSync(join(app, '.claude/skills')) ? readdirSync(join(app, '.claude/skills')) : []
check(
  linked.exitCode === 0 && skills.every((skill) => linkedSkills.includes(skill)),
  'skills-npm links every shipped skill into .claude/skills',
)
check(
  skills.every((skill) => existsSync(join(app, '.claude/skills', skill, 'references'))),
  'linked skills include their references',
)

if (args.includes('--keep')) console.log(`Kept ${work}`)
else rmSync(work, { recursive: true, force: true })

if (failures.length) {
  console.error(`\n${failures.length} check(s) failed`)
  process.exit(1)
}
console.log('\nAll package checks passed')
